/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountState: typeof import('./src/components/AccountState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuiEnokiPlugins: typeof import('./src/components/SuiEnokiPlugins.vue')['default']
    SuiEnokiRedirect: typeof import('./src/components/SuiEnokiRedirect.vue')['default']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    ULinkBase: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UNavigationMenu: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.0.0-alpha.9_@babel+core@7.26.0_@babel+parser@7.26.2_embla-carousel@8.5.1_magicast@_3ufbt3bda2jc57w34o4z5r3rmq/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  }
}
